// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Essay: typeof import('./../components/Essay.vue')['default']
    FullResolutionAdaptationAndResponsiveDesign: typeof import('./../pages/Full-resolution-adaptation-and-responsive-design.md')['default']
    HowToDefineAFunction: typeof import('./../pages/How-to-define-a-function.md')['default']
    'IconIc:twotoneArrowBack': typeof import('~icons/ic/twotone-arrow-back')['default']
    'IconIc:twotoneArrowForward': typeof import('~icons/ic/twotone-arrow-forward')['default']
    'IconIc:twotoneArrowUpward': typeof import('~icons/ic/twotone-arrow-upward')['default']
    IconMdiBookOpenOutline: typeof import('~icons/mdi/book-open-outline')['default']
    IntroductionToComposables: typeof import('./../pages/Introduction-to-Composables.md')['default']
    JavaScriptMemo: typeof import('./../pages/JavaScript-memo.md')['default']
    MyButton: typeof import('./../components/MyButton.vue')['default']
    MyPagination: typeof import('./../components/MyPagination.vue')['default']
    MyTag: typeof import('./../components/MyTag.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NaiveProvider: typeof import('./../components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NResult: typeof import('naive-ui')['NResult']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeScriptMemo: typeof import('./../pages/TypeScript-memo.md')['default']
  }
}
